for i=1:length(AllTrainingData{1,1})
    sbj_id{i} = AllTrainingData{1,1}(1,i).sbj_name;
end
for j=i+1:length(AllTestingData{1,1})+i
    sbj_id{j} = AllTestingData{1,1}(1,j-i).sbj_name;
end

features = {'L Hippo Volume','L Hippo M11', 'L Hippo M12', 'L Hippo M22', 'L Hippo Entropy',...
    'R Hippo Volume','R Hippo M11', 'R Hippo M12', 'R Hippo M22', 'R Hippo Entropy',...
    'LiL Vent Volume','LiL Vent M11', 'LiL Vent M12', 'LiL Vent M22', 'LiL Vent Entropy',...
    'RiL Vent Volume','RiL Vent M11', 'RiL Vent M12', 'RiL Vent M22', 'RiL Vent Entropy',...
    'RL Vent Volume','RL Vent M11', 'RL Vent M12', 'RL Vent M22', 'RL Vent Entropy',...
    '3rd Vent Volume','3rd Vent M11', '3rd Vent M12', '3rd Vent M22', '3rd Vent Entropy',...
    'L Amyg Volume','L Amyg M11', 'L Amyg M12', 'L Amyg M22', 'L Amyg Entropy',...
    'R Amyg Volume','R Amyg M11', 'R Amyg M12', 'R Amyg M22', 'R Amyg Entropy',...
    'LC WM Volume', 'RC WM Volume'};